[package]
name = "zelda"
description = "Zelda, a lightweight application-level network protocol for use in real-time applications."
version = "0.1.2"
license = "MIT"
authors = ["oskarbraten <oskar.braten@outlook.com>"]
readme = "README.md"
documentation = "https://docs.rs/zelda"
repository = "https://github.com/oskarbraten/zelda"
edition = "2018"

[dependencies]
num-traits = "0.2"
crossbeam = "0.8.0"
dashmap = "4.0.2"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.2"