[package]
name = "oberon-net"
version = "0.1.0"
authors = ["oskarbraten <oskar.braten@outlook.com>"]
edition = "2018"

[dependencies]
slab = "0.4.2"
crossbeam = "0.7.2"
chashmap = "2.2.2"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.0"