[package]
name = "zelda"
description = "Zelda, a lightweight application-level network protocol for use in real-time applications."
version = "0.2.0"
license = "MIT"
authors = ["oskarbraten <oskar.braten@outlook.com>"]
readme = "README.md"
documentation = "https://docs.rs/zelda"
repository = "https://github.com/oskarbraten/zelda"
edition = "2018"

[dependencies]
tokio = { version = "1.4.0", features = ["full"] }
async-channel = "1.6.1"
byteorder = "1.4.3"
crossbeam = "0.8.0"
dashmap = "4.0.2"
slab = "0.4.2"
rand = "0.8.3"
cmac = "0.5.1"
aes = "0.6.0"
anyhow = "1.0.40"