[package]
name = "zelda"
description = """
Zelda is a lightweight application-level network protocol for use in real-time applications.
"""
version = "0.1.1"
license = "MIT"
authors = ["oskarbraten <oskar.braten@outlook.com>"]
readme = "README.md"
documentation = "https://docs.rs/zelda"
repository = "https://github.com/oskarbraten/zelda"
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
crossbeam = "0.7.2"
chashmap = "2.2.2"
linked-hash-map = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.0"